created 'our mission' component, contains title text
acm-ucr/witl-website pull request #22
Opened 2024-06-28 05:29 UTC by FelixMDM

2024-06-28 17:52 UTC, FelixMDM commented
![image](https://github.com/acm-ucr/witl-website/assets/122497855/2601d2ac-bb5b-4aab-afa6-54c3df3a916f)

2024-06-28 20:29 UTC, stanleylew5 requested changes

2024-06-28 20:29 UTC, stanleylew5 commented on src/components/OurMission.jsx
> +      <p className="m-auto p-auto font-serif text-7xl">Our Mission</p>
pull from dev and change the font family to match what's on the figma

2024-06-29 04:45 UTC, stanleylew5 reviewed
let's call this component in our page.js file in the about folder, other than that it looks good to me

2024-06-29 06:44 UTC, merged