justin-h-im/about page
acm-ucr/witl-website pull request #38
Opened 2024-07-01 20:11 UTC by justin-h-im

Created basis for the About Us title page. 
Images for Code Changes: 
![image](https://github.com/acm-ucr/witl-website/assets/93964548/1dd6aed3-4c81-4f89-a650-2444ba7046a8)
![image](https://github.com/acm-ucr/witl-website/assets/93964548/43ac6911-e932-48ba-ae1f-1932f171844c)

Images for Product on Local Host:
![image](https://github.com/acm-ucr/witl-website/assets/93964548/ea8843c3-8c63-4f94-a836-0b47ed90f687)

2024-07-01 22:08 UTC, stanleylew5 commented on src/app/about/page.js
> +import "@/app/layout.js";
```suggestion

```

2024-07-01 22:13 UTC, stanleylew5 requested changes

2024-07-01 22:13 UTC, stanleylew5 commented on src/app/about/page.js
> +import "@/app/layout.js";
```suggestion

```

2024-07-01 22:13 UTC, stanleylew5 commented on src/app/about/page.js
> +import "@/app/layout.js";
not needed as layout.js is already applied

2024-07-01 22:13 UTC, stanleylew5 commented on src/app/about/page.js
> +export default About;
change the exporting back to page and move your code to an About.jsx file

2024-07-01 22:13 UTC, stanleylew5 commented on tailwind.config.js
> +    }),
```suggestion
   
```

2024-07-01 22:13 UTC, stanleylew5 commented on tailwind.config.js
> +    }),
not needed, if you wanted to use this color as a background color use one of the already defined colors with tailwind

the class would be bg-witl-purple-300 (check above for already defined colors)

2024-07-01 22:13 UTC, stanleylew5 commented on src/app/about/page.js
> +    <div className="bg-purplecustom min-h-screen flex items-center justify-center">
```suggestion
    <div className="bg-witl-purple-300 min-h-screen flex items-center justify-center">
```

2024-07-01 22:13 UTC, stanleylew5 commented on src/app/about/page.js
> +        <div className="mb-1 text-9xl text-center text-purple-200">
use witl colors

2024-07-01 22:13 UTC, stanleylew5 commented on src/app/about/page.js
> +        <div className="mb-1 text-9xl text-center text-purple-200">
use witl colors

2024-07-02 00:55 UTC, justin-h-im commented
Updated work to put everything into a jsx file, corrected colors, merged with dev on this branch.

Code Screenshots:
![image](https://github.com/acm-ucr/witl-website/assets/93964548/a2c664e6-9144-4415-8736-bfceb57f5935)
![image](https://github.com/acm-ucr/witl-website/assets/93964548/d667291d-1355-4dd9-9540-beac28e3aa3e)

Output Screenshots:
![image](https://github.com/acm-ucr/witl-website/assets/93964548/0be462f2-dcde-48da-a38b-014fdaf2fd20)

2024-07-02 01:01 UTC, merged