added ourmission grid
acm-ucr/witl-website pull request #52
Opened 2024-07-08 22:33 UTC by andrew3521

<img width="1345" alt="Screenshot 2024-07-08 at 3 32 06 PM" src="https://github.com/acm-ucr/witl-website/assets/168773770/d176d280-112b-4430-92e2-0310251fc111">

2024-07-08 23:21 UTC, stanleylew5 requested changes
add a line break after

The X in womxn honors women’s intersecting identities, as women in America are impacted by a multitude of social justice and human rights issues. - Kimberlé Crenshaw

also try and get the image's height to be the same height as the text 

please pull from your own branch before you start coding

git pull origin andrew3521/mission

2024-07-09 03:30 UTC, andrew3521 commented
<img width="1440" alt="Screenshot 2024-07-08 at 8 28 44 PM" src="https://github.com/acm-ucr/witl-website/assets/168773770/3bc02200-826d-4145-9faa-5b29ff53b34f">
<img width="1440" alt="Screenshot 2024-07-08 at 8 28 44 PM" src="https://github.com/acm-ucr/witl-website/assets/168773770/c1a9760d-ac8b-49e2-903b-31785c48d5cb">

2024-07-09 05:08 UTC, stanleylew5 requested changes

2024-07-09 05:08 UTC, stanleylew5 commented on src/components/about/OurMission.jsx
> +        <div className="pl-52 pt-8">
let's not hard code values like pl-52 use flex and justify-end and then add like padding values of four

2024-07-09 05:08 UTC, stanleylew5 commented on src/components/about/OurMission.jsx
> +    <div>
add some padding beneath your div like pb-2

2024-07-09 05:08 UTC, stanleylew5 commented on src/components/Dummy.jsx
> +export default Dummy;
delete this file

2024-07-09 21:14 UTC, andrew3521 commented
![image](https://github.com/acm-ucr/witl-website/assets/168773770/063ac1fa-fdf5-4d6e-bce3-f5094e67b9a0)

2024-07-09 23:36 UTC, merged